/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.turing.javase7.javase7thbatch.movieapp.ui;

import com.turing.javase7.javase7thbatch.movieapp.dao.model.Genre;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Movie;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Rating;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.User;
import com.turing.javase7.javase7thbatch.movieapp.service.App;
import com.turing.javase7.javase7thbatch.movieapp.service.AuthService;
import com.turing.javase7.javase7thbatch.movieapp.service.GenreService;
import com.turing.javase7.javase7thbatch.movieapp.service.MovieService;
import com.turing.javase7.javase7thbatch.movieapp.service.RatingService;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class MovieRating extends javax.swing.JFrame {

    App app = App.getSingleton();
    
    MovieService movieService = app.getMovieService();
    GenreService genreService = app.getGenreService();
    RatingService ratingService = app.getRatingService();
    AuthService authService = app.getAuthService();
    /**
     * Creates new form MovieRating
     */
    public MovieRating() {
        initComponents();
        this.loadMovies();
       
        //this.loadRatingForUser(user.id());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboRating = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMovieRating = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        btnAddRating = new javax.swing.JButton();

        jLabel1.setText("Rating");

        cboRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        tblMovieRating.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "UserId", "MovieID", "Rating"
            }
        ));
        jScrollPane2.setViewportView(tblMovieRating);

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Year", "Genres"
            }
        ));
        jScrollPane3.setViewportView(tblMovies);

        btnAddRating.setText("Add Rating");
        btnAddRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRatingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddRating, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(cboRating, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnAddRating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void addRating()
    {
        User user = this.authService.getAuthUser();
        int row = this.tblMovies.getSelectedRow();
        if(row !=-1)
        {
            Integer movieId = (Integer)this.tblMovies.getModel().getValueAt(row, 0);
            int rating = Integer.parseInt(this.cboRating.getSelectedItem().toString());
            
            this.ratingService.addRating(user.id(), movieId, rating);
            this.loadRatingForUser(user.id());
        }
    }
    private void btnAddRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRatingActionPerformed
        // TODO add your handling code here:
        this.addRating();
    }//GEN-LAST:event_btnAddRatingActionPerformed
    void loadMovies()
    {
        ArrayList<Movie> movies = this.movieService.getAllMovie();
        System.out.println("Movie size "+movies.size());
        DefaultTableModel model = (DefaultTableModel)this.tblMovies.getModel();
        
        model.setRowCount(0);
        
        for(Movie movie : movies)
        {
            Object[]row = new Object[4];
            row[0] = movie.id();
            row[1] =movie.title();
            row[2] = movie.year();
            row[3] = this.getGenresForMovie(movie.id());
            
            model.addRow(row);
        }
    }
    public void loadRatingForUser(int userId)
    {
        ArrayList<Rating> ratings = this.ratingService.getAllRatingByUser(userId);
        System.out.println("Movie size "+ratings.size());
        DefaultTableModel model = (DefaultTableModel)this.tblMovieRating.getModel();
        
        model.setRowCount(0);
        
        for(Rating rating : ratings)
        {
            Object[]row = new Object[4];
            row[0] = rating.id();
            row[1] =rating.userId();
            row[2] = rating.movieId();
            row[3] = rating.rating();
            
            model.addRow(row);
        }
    }
    String getGenresForMovie(int movieId)
    {
        ArrayList<Genre> genres = this.genreService.getAllGenresByMovieId(movieId);
        String str = "";
        
        for(Genre genre : genres)
        {
            if(str.length()>0)
            {
                str += ", "+ genre.name();
            }
            else
            {
                str = genre.name();
            }
        }
        return str;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieRating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieRating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieRating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieRating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieRating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRating;
    private javax.swing.JComboBox<String> cboRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMovieRating;
    private javax.swing.JTable tblMovies;
    // End of variables declaration//GEN-END:variables
}
