/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.turing.javase7.javase7thbatch.movieapp.ui;

import com.turing.javase7.javase7thbatch.movieapp.dao.model.Genre;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Movie;
import com.turing.javase7.javase7thbatch.movieapp.service.App;
import com.turing.javase7.javase7thbatch.movieapp.service.GenreService;
import com.turing.javase7.javase7thbatch.movieapp.service.MovieService;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class MovieWithActorDirector extends javax.swing.JFrame {
    App app = App.getSingleton();
    
    MovieService movieService = app.getMovieService();
    GenreService genreService = app.getGenreService();
    /**
     * Creates new form MovieWithActor
     */
    public MovieWithActorDirector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Year", "Genres"
            }
        ));
        jScrollPane1.setViewportView(tblMovies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showMovieForActor(int actorId)
    {
        ArrayList<Movie> movies = this.movieService.getAllMovieWhichIncludeActor(actorId);
        System.out.println("Movie size "+movies.size());
        DefaultTableModel model = (DefaultTableModel)this.tblMovies.getModel();
        
        model.setRowCount(0);
        
        for(Movie movie : movies)
        {
            Object[]row = new Object[4];
            row[0] = movie.id();
            row[1] =movie.title();
            row[2] = movie.year();
            row[3] = this.getGenresForMovie(movie.id());
            
            model.addRow(row);
        }
    }
    public void showMovieForDirector(int directorId)
    {
        ArrayList<Movie> movies = this.movieService.getAllMovieByDirector(directorId);
        System.out.println("Movie size "+movies.size());
        DefaultTableModel model = (DefaultTableModel)this.tblMovies.getModel();
        
        model.setRowCount(0);
        
        for(Movie movie : movies)
        {
            Object[]row = new Object[4];
            row[0] = movie.id();
            row[1] =movie.title();
            row[2] = movie.year();
            row[3] = this.getGenresForMovie(movie.id());
            
            model.addRow(row);
        }
    }
    String getGenresForMovie(int movieId)
    {
        ArrayList<Genre> genres = this.genreService.getAllGenresByMovieId(movieId);
        String str = "";
        
        for(Genre genre : genres)
        {
            if(str.length()>0)
            {
                str += ", "+ genre.name();
            }
            else
            {
                str = genre.name();
            }
        }
        return str;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieWithActorDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieWithActorDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieWithActorDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieWithActorDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieWithActorDirector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMovies;
    // End of variables declaration//GEN-END:variables
}
