/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.turing.javase7.javase7thbatch.movieapp.ui;

import com.turing.javase7.javase7thbatch.movieapp.dao.model.Actor;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Director;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Genre;
import com.turing.javase7.javase7thbatch.movieapp.dao.model.Movie;
import com.turing.javase7.javase7thbatch.movieapp.service.ActorService;
import com.turing.javase7.javase7thbatch.movieapp.service.App;
import com.turing.javase7.javase7thbatch.movieapp.service.DirectorService;
import com.turing.javase7.javase7thbatch.movieapp.service.GenreService;
import com.turing.javase7.javase7thbatch.movieapp.service.MovieService;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author macbook
 */
public class MovieSetup extends javax.swing.JFrame implements TableModelListener, ListSelectionListener{

    App app = App.getSingleton();
    
    MovieService movieService = app.getMovieService();
    GenreService genreService = app.getGenreService();
    ActorService actorService = app.getActorService();
    DirectorService directorService = app.getDirectorService();
    
    HashMap<String,Integer> genereAndId = new HashMap<String,Integer>();
    HashMap<String,Integer> actorAndId = new HashMap<String,Integer>();
    HashMap<String,Integer> directorAndId = new HashMap<String,Integer>();
    /**
     * Creates new form MovieSetup
     */
    public MovieSetup() {
        initComponents();
        this.loadMovies();
        this.loadGenresToComboBox();
        this.loadActorComboBox();
        this.loadDirectorComboBox();
        
        this.tblMovies.getModel().addTableModelListener(this);
        this.tblMovies.getSelectionModel().addListSelectionListener(this);
    }
    void loadGenresToComboBox()
    {
        ArrayList<Genre> genres = this.genreService.getAllGenres();
        for(Genre genre : genres)
        {
            this.cboGenres.addItem(genre.name());
            this.genereAndId.put(genre.name(), genre.id());
        }
    }
    
    void loadActorComboBox()
    {
        ArrayList<Actor> actors =this.actorService.getAllActors();
        System.out.println("Actor size "+actors.size());
        
        
        for(Actor actor : actors)
        {
            
            this.cboActors.addItem(actor.name());
            this.actorAndId.put(actor.name() , actor.id());
            
        }
       
    }
    void loadDirectorComboBox()
    {
        ArrayList<Director> directors =this.directorService.getAllDirector();
        System.out.println("directors size "+directors.size());
        
        
        for(Director director : directors)
        {
            
            this.cboDirector.addItem(director.name());
            this.directorAndId.put(director.name() , director.id());
            
        }
       
    }
    void loadMovies()
    {
        ArrayList<Movie> movies = this.movieService.getAllMovie();
        System.out.println("Movie size "+movies.size());
        DefaultTableModel model = (DefaultTableModel)this.tblMovies.getModel();
        
        model.setRowCount(0);
        
        for(Movie movie : movies)
        {
            Object[]row = new Object[4];
            row[0] = movie.id();
            row[1] =movie.title();
            row[2] = movie.year();
            row[3] = this.getGenresForMovie(movie.id());
            
            model.addRow(row);
        }
    }
    String getGenresForMovie(int movieId)
    {
        ArrayList<Genre> genres = this.genreService.getAllGenresByMovieId(movieId);
        String str = "";
        
        for(Genre genre : genres)
        {
            if(str.length()>0)
            {
                str += ", "+ genre.name();
            }
            else
            {
                str = genre.name();
            }
        }
        return str;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAddGenre = new javax.swing.JButton();
        cboGenres = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboActors = new javax.swing.JComboBox<>();
        btnAddActorToMovie = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActorInMovie = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDirectorInMovie = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cboDirector = new javax.swing.JComboBox<>();
        btnAddDirector = new javax.swing.JButton();

        setTitle("Movie Setup");

        jLabel1.setText("Title");

        jLabel2.setText("Year");

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Year", "Genres"
            }
        ));
        jScrollPane1.setViewportView(tblMovies);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("Genres");

        btnAddGenre.setText("Add Genre");
        btnAddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddGenre)
                    .addComponent(cboGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboGenres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddGenre)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel4.setText("Actor");

        btnAddActorToMovie.setText("Add Actor");
        btnAddActorToMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActorToMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddActorToMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(cboActors, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddActorToMovie)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel5.setText("Actor in movie");

        jScrollPane2.setViewportView(lstActorInMovie);

        jLabel6.setText("Director in movie");

        jScrollPane3.setViewportView(lstDirectorInMovie);

        jLabel7.setText("Director");

        btnAddDirector.setText("Add Director");
        btnAddDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(cboDirector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddDirector)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnDelete)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void addMovie()
    {
        String title = this.txtTitle.getText();
        int year = Integer.parseInt(this.txtYear.getText());
       
        this.movieService.addMovie(title, year);
        
        this.loadMovies();
        this.clearForm();
        
    }
    void clearForm()
    {
        this.txtTitle.setText("");
        this.txtYear.setText("");
    }
    void deleteMovie()
    {
        int row = this.tblMovies.getSelectedRow();
        if(row !=-1)
        {
            int result = JOptionPane.showConfirmDialog(null, "Delete", "Are you sure you want to delete", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION)
            {
                Integer id = (Integer)this.tblMovies.getModel().getValueAt(row, 0);
                
                this.movieService.deleteMovieById(id);
                
                this.loadMovies();
            }
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.addMovie();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.deleteMovie();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenreActionPerformed
        // TODO add your handling code here:
        this.addGenreToMovie();
    }//GEN-LAST:event_btnAddGenreActionPerformed
    void addGenreToMovie()
    {
        int row = this.tblMovies.getSelectedRow();
        if(row !=-1)
        {
            Integer movieId = (Integer)this.tblMovies.getModel().getValueAt(row, 0);
            String genre = (String)this.cboGenres.getSelectedItem();
            Integer genreId = this.genereAndId.get(genre);
            System.out.println("Movie id "+movieId+" genre id "+genreId);
            
            this.movieService.addGenereToMovie(movieId,genreId);
            this.loadMovies();
            JOptionPane.showMessageDialog(null, "Genre successfully added");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select movie to add genre");
        }
    }
    
    private void btnAddActorToMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActorToMovieActionPerformed
        // TODO add your handling code here:
        this.addActorToMovie();
    }//GEN-LAST:event_btnAddActorToMovieActionPerformed

    private void btnAddDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirectorActionPerformed
        // TODO add your handling code here:
        this.addDirectorToMovie();
    }//GEN-LAST:event_btnAddDirectorActionPerformed
    void addActorToMovie()
    {
        int row = this.tblMovies.getSelectedRow();
        if(row !=-1)
        {
            Integer movieId = (Integer)this.tblMovies.getModel().getValueAt(row, 0);
            String actor = (String)this.cboActors.getSelectedItem();
            Integer genreId = this.actorAndId.get(actor);
            System.out.println("Movie id "+movieId+" actor id "+genreId);
            
            this.movieService.addActorToMovie(movieId,genreId);
            this.loadActorForMovie(movieId);
            JOptionPane.showMessageDialog(null, "Actor successfully added");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select movie to add genre");
        }
    }
    void addDirectorToMovie()
    {
        int row = this.tblMovies.getSelectedRow();
        if(row !=-1)
        {
            Integer movieId = (Integer)this.tblMovies.getModel().getValueAt(row, 0);
            String director = (String)this.cboDirector.getSelectedItem();
            Integer directorId = this.directorAndId.get(director);
            System.out.println("Movie id "+movieId+" directorId id "+directorId);
            
            this.movieService.addDirectorToMovie(movieId,directorId);
            this.loadDirectorForMovie(movieId);
            JOptionPane.showMessageDialog(null, "Actor successfully added");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select movie to add genre");
        }
    }
    void loadDirectorForMovie(int movieId)
    {
        ArrayList<Director> directors = this.movieService.getAllDirectorForMovie(movieId);
        this.showDirectorForMovie(directors);
        
    }
    void showDirectorForMovie(ArrayList<Director> directors)
    {
        Vector listModel = new Vector();
        for(Director director : directors)
        {
            listModel.addElement(director.name());
            
        }
        this.lstDirectorInMovie.setListData(listModel);
    }
    void loadActorForMovie(int movieId)
    {
        ArrayList<Actor> actors = this.movieService.getAllActorForMovie(movieId);
        this.showActorForMovie(actors);
    }
    void showActorForMovie(ArrayList<Actor> actors)
    {
        Vector listModel = new Vector();
        for(Actor actor : actors)
        {
            listModel.addElement(actor.name());
            
        }
        this.lstActorInMovie.setListData(listModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddActorToMovie;
    private javax.swing.JButton btnAddDirector;
    private javax.swing.JButton btnAddGenre;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cboActors;
    private javax.swing.JComboBox<String> cboDirector;
    private javax.swing.JComboBox<String> cboGenres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstActorInMovie;
    private javax.swing.JList<String> lstDirectorInMovie;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    @Override
   
    public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        if (e.getType() == TableModelEvent.UPDATE) {
            TableModel model = (TableModel) e.getSource();
            Integer id = (Integer)model.getValueAt(row, 0);
            String title = (String)model.getValueAt(row, 1);
            Integer year = (Integer) model.getValueAt(row, 2);
            
            Movie updateMovie = new Movie(id,title,year);
            // Perform actions based on the updated data, e.g., update a database
            System.out.println("Cell updated at [" + row + ", " + column + "]: " );
            
            this.movieService.updateMovie(updateMovie);
            
        }
        // Handle INSERT and DELETE events similarly
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            int selectedRow = this.tblMovies.getSelectedRow();
            if (selectedRow != -1) {
                // A row is selected
                System.out.println("Selection changed. Selected row: " + selectedRow);

                // Example: Get data from the first column of the selected row
                Integer movieId = (Integer)tblMovies.getModel().getValueAt(selectedRow, 0);
                System.out.println("Value in first column: " + movieId);
                this.loadActorForMovie(movieId);
                this.loadDirectorForMovie(movieId);
            }
        }
    }
    
}
